### ISSUE TITLE
Discussion: Community Registration

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#204]
Ideal properties for registering community names may include:

1. ability to claim a community name based on their subjective capacity to lead
2. ability to reclaim ownership of a community which has ceased activity
3. decentralized: no central entity is controlling registration or collecting payments

## Potential Models

(Not a complete list, just a start for discussion.)

### 1. NCI: Numerical Community Identifier

Under this model, all communities are identified by a numerical id. This avoids the issue of name claiming and squatting entirely. The id should be explicit in the creation op, so a concern is how to resolve potential conflicts. One option is to prefix the id with the creator's account name converted to base 10.

Posts to the community must reference the NCI. Community URLs would simply be e.g. https://steempeak.com/18221929. Each frontend could implement human-friendly names as they see fit. There could be a separate committee which handles recommended NCI to name mapping. This model is akin to communities being IP addresses, leaving DNS as a separate exercise.

### 2. Account Names

The original spec suggested that community names be based on account names; this fulfills property (3) but negates (2) and doesn't address (1).

### 3. Harberger Tax

A modified Harberger Tax model with a multiplier which makes it (e.g. 90%) cheaper to maintain a name once you own it. See [more info](https://medium.com/@simondlr/what-is-harberger-tax-where-does-the-blockchain-fit-in-1329046922c6) and [example implementation on r/ethtrader](<https://www.reddit.com/r/ethtrader/comments/a3r1bn/you_can_now_change_the_top_banner_on_the_redesign/>).

Perhaps it costs 10X the purchase price to reclaim a name. And the purchase price has to be paid every 6 months to maintain ownership. Example: user A pays 20 SBD to claim `carsandtrucks`. They get to keep the name as long as they continue to pay 20 SBD every 6 months, unless someone claims ownership of it for 200 SBD. That user will then have to pay 200 SBD every 6 months or risk losing it.

There are ways to abuse this system, but we can consider adding some protections. This model can get complicated however, and the funds most likely need to be burnt to achieve property (3). 

### 4. Hardcoded names

Under this model, the initial set of community owners and names would become part of the initial spec. It allows us to continue forward and defer an advanced naming system to a later date.

### 5. Naming Committee

A group of users responsible for approving names is encoded into the original spec. Users could apply to create a community, specifying basic details and the desired name. The committee has to reach majority approval for it to become official. This could also be implemented as a single account with multisig permissions which is responsible for publishing ownership/names map. However multisig tooling is currently lacking.

**Comment by asgarth** [comment]
In my opinion the only viable solution that is easy to implement and to maintain is the first one.

I'm not a fan of option 3, and both 4 and 5 are not really decentralized solutions to the problem.

**Comment by photodeca** [comment]
Number 1 may be a viable solution... 

So let's talk about the issues with #1 
A. a dozen communities called "photography"
B. lots of opportunities for scamming people using names of trusted companies etc... in order to pose as that company/person. etc
C. A billion communities created possibly diluting attention
D. URLs are not attractive, interesting or SEO friendly

**Comment by photodeca** [comment]
OPTION 6
1. Business vs Open Community accounts  ... or Private vs Open
meaning put a letter before the URL   /P/bhphoto  -   /O/photography
2. Payment for creating a business account... payment money either gets burned OR goes to Steem Proposals system
3. Allow people to transfer ownership to an account. Essentially they could sell that right of ownership. Usually I'd say it should be a token but not sure if that's a sore subject since we don't have Steemit based SMTs ... my normal reply would be use a Steem-Engine token that has a quantity of like 1. Something like that. 
4. For communities to avoid dilution I think there should be a bar for entry. I think to keep that bar decentralized perhaps it could be set at first but then during a hard fork the witnesses could add a number of what they think needs to be the entry point for open community. Let's say 10 users need to request that this community exist.  
5.Then i believe that a group consisting of multiple parts should run an action when we launch that grabs/mines a huge list of Private community names and takes care of them for future possible usage by those companies. Pepsi, Samsung, Google, Nike, MLB, NFL, Argentina, Pewdiepie ... etc
Users could help us grow the list making suggestions etc for their countries
Grabbing them is just one part of it... however later we can make the tech needed to allow the group sign off on transfering ownership to a verified party. 


Ok that's the first run on option 6
I have to go to a meeting i'll think about it more or ask some questions so we can keep it going.

**Comment by roadscape** [comment]
@photodeca in regards to your concerns with model (1):
A. It would become clear which ones are authoritative based on stats (subscribers, payouts).
B. Steem has a standard for account "Display Names" which are not required to be unique, and cases of abuse are quite limited.
C. registration could still be rate limited, and no need to show all communities all the time. (e.g. even though we have 1M+ accounts of which many are inactive doesn't take away attention from the active ones)
D. URLs are left as a separate exercise. Nothing precludes us from adopting a more complex model like your Option (6).

**Comment by roadscape** [comment]
What's useful about the NCI approach (the first model) is that it allows changing names in the future without destroying community-content relationships. If a name is reassigned, all the numerical identifiers on chain are still accurate. In a traditional database you would easily update all old posts to have some new name. With a chain db it's much wiser to use a future-proof id.

Model (1) would allow us to move forward immediately, and leave options open for how to implement naming. Worst case scenario, initial launch could use numerical URLs.

**Comment by roadscape** [comment]
Thinking further a naming system on top of model (1), here are some considerations:

1. How do users lay claim to an unused name?
2. How do users submit a claim on a used name?
3. Does the owner of a reclaimed name get a refund?
4. Does the whole community get transferred, or do they simply lose their name?
   - If transferred: non-starter.. due to use of force
   - If name is lost: how are subscribers notified?

The main conclusion here is that *reassignments must be rare because they create chaos*.

To avoid reassignments:

1. reassignments must be costly
2. thoughtless registrations (squatting) must be minimized (assignments should be costly)
3. names which are likely to be otherwise reassigned should be more costly

---

It seems wise to have all communities start out with a numerical URL. Allowing communities to demonstrate their prowess first will provide useful insight into naming priorities. Subjectively to some sort of committee, and/or objectively through metrics such as engagement and payouts.

**Comment by roadscape** [comment]
The main concern with NCI is now to ensure there are no conflicts when registering an id number.  For this we could leverage the account namespace, without pollution, by using a specific format -- e.g. `/^cmt-[1-9]\d{4,6}$/`. In this case the valid range would be `cmt-10000` to `cmt-9999999` for a total of 9.99M possible id's.

This account could also be considered the admin. Community "subscriptions" could reuse the follows mechanism. Either high-sec settings such as `admins`, `type`, and `reward_split` or community metadata can be stored on the account's `json_metadata` field.

**Comment by roadscape** [comment]
More feedback is welcome but moving forward with this approach for updated spec.

**Comment by photodeca** [comment]
> D. URLs are left as a separate exercise. Nothing precludes us from adopting a more complex model like your Option (6).

Well that does make NCI more appealing with this compromise.
