### ISSUE TITLE
fast block sync w/ jussi

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#5]
Add new sync strategy: sync from jussi, if it's configured. It allows us to request blocks in large batches.

**Comment by roadscape** [comment]
api.steemitdev.com tests:

batch size - blocks/s
1 - 6
10 - 46
100 - 256
1000 - 600
2000 - 610

**Comment by roadscape** [comment]
I get 4400 blocks/s using ws directly to a local steemd

**Comment by sneak** [comment]
i'm going to speculate that this is due to redis roundtrip time and the fact that it is making single redis calls to get individual blocks; if it batches redis calls it should go a lot faster. however, it's worth noting that while you only get 500-600 blocks/sec from it presently, the steemd that gives you 4400/sec can't do anything else at the same time...

**Comment by roadscape** [comment]
https://github.com/steemit/hivemind/pull/17
