### ISSUE TITLE
Project Split [Proposal]

### ISSUE THREAD

**Issue by hernandev** [steemit/hivemind#97]
Instead of API server and blockchain streaming/parsing being done by the same project, would not be wise to separate the projects?

Even if related to the same database structure, It does not makes sense to me, using a unified approach on this.

Also, it would be easier for external contributions when codebase is not mixed.

**Comment by relativityboy** [comment]
At some point this could make sense but for now having them integrated is an accurate reflection of where the project is at. Hive is designed for communities. The database and the "parsing of the blockchain" as you called it is done for communities. It's all oriented toward communities, and so should be in the same codebase. 

You can always contribute and put in notes with a "here is a good place that we could separate concerns.". You could even fork the repo and show us how it should be done. 

Otherwise, I'd suggest bringing it up again once communities has been in production for a while. At that point we'll have a better understanding of the appropriate components to break out.

**Comment by hernandev** [comment]
ok got it @relativityboy thank you.

**Comment by roadscape** [comment]
Hi @hernandev, to add to @relativityboy's comment -- the indexing service and API service do have minimal coupling (mainly just schema) to leave open these sorts of opportunities in the future. Also, using the bundled API server is optional; one could easily write a separate service (in any language) to serve data from the Postgres db.
